CC := gcc
LD_LIBRARY_PATH := /home/subodha/m5thread-gem5/m5threads
CFLAGS := -O3 -D_POSIX_C_SOURCE=200112
#CFLAGS := -O3 -pthread -D_POSIX_C_SOURCE=200112 #we had this earlier
#CFLAGS := -g3 -pthread -D_POSIX_C_SOURCE=200112
CFLAGS := $(CFLAGS) -Wall -W -Wmissing-prototypes -Wmissing-declarations -Wredundant-decls -Wdisabled-optimization
CFLAGS := $(CFLAGS) -Wpadded -Winline -Wpointer-arith -Wsign-compare -Wendif-labels
LDFLAGS := -lm

BASEDIR := /home/subodha/resources-gem5/benchmarks/splash2/codes
MACROS := $(BASEDIR)/null_macros/c.m4.null.POSIX_BARRIER
M4 := m4 -s -Ulen -Uindex

x = *

$(TARGET): $(OBJS)
	$(CC) $(OBJS) /home/subodha/m5thread-gem5/m5threads/pthread.o $(CFLAGS) -o $(TARGET) $(LDFLAGS) -static

clean:
	rm -rf *.c *.h *.o $(TARGET)

.SUFFIXES:
.SUFFIXES:	.o .c .C .h .H

.H.h:
	$(M4) $(MACROS) $*.H > $*.h

.C.c:
	$(M4) $(MACROS) $*.C > $*.c

.c.o:
	$(CC) -c $(CFLAGS) $*.c

.C.o:
	$(M4) $(MACROS) $*.C > $*.c
	$(CC) -c $(CFLAGS) $*.c
